pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: node:8-alpine
    pull: true
    when:
      event: 
        - pull_request
        - tag

    commands:
      - npm install
      - npm test -- --coverage


  code-cov:
    image: robertstettner/drone-codecov
    when:
      event: 
        - pull_request
        - tag

    secrets: [ codecov_token ]
    token: $${codecov_token}
    files:
      - ./coverage/lcov.info


  rebuild-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    rebuild: true
    mount:
      - ./node_modules

    volumes:
      - /tmp/cache:/cache