pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: node
    pull: true
    when:
      event: 
        - push
        - pull_request
        - tag

    commands:
      - npm install
      - npm test -- --coverage

  upload-cov:
    image: node
    pull: true
    secrets: [ codecov_token ]
    when:
      event: 
        - push
        - tag

    commands:
      - npm install -g codecov
      - codecov -t $${CODECOV_TOKEN}

  rebuild-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    rebuild: true
    mount:
      - ./node_modules

    volumes:
      - /tmp/cache:/cache